name: Build VLC-Android LibVLC arm64

on:
  workflow_dispatch: 

jobs:
  build-libvlc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '8512546'         # 你当前的 SDK 版本可以保留
          ndk-version: '21.4.7075529'    # NDK 21 版本

      - name: Add sdkmanager to PATH
        run: echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y automake ant autopoint cmake build-essential libtool-bin \
            patch pkg-config protobuf-compiler ragel subversion unzip git \
            openjdk-8-jre openjdk-8-jdk flex python3 wget ninja-build meson \
            libxml2-utils xmlto gettext intltool
            
      - name: Configure git user
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"
          
      - name: Build LibVLC for arm64
        run: |
          export ANDROID_SDK=$ANDROID_SDK_ROOT
          export ANDROID_NDK=$ANDROID_NDK_ROOT
          chmod +x buildsystem/compile.sh
          ./buildsystem/compile.sh -vlc4 -l -a arm64 -r

      - name: Create release zip
        run: |
          mkdir -p release_files/include
          cp libvlcjni/libvlc/libs/arm64-v8a/libvlc.so release_files/
          cp libvlcjni/libvlc/libs/arm64-v8a/libvlcjni.so release_files/
          cp libvlcjni/vlc/include/vlc/*.h release_files/include/
          cd release_files
          zip -r ../vlc-libvlc-arm64.zip .
          cd ..

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: vlc-libvlc-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
