name: Build VLC-Android LibVLC arm64

on:
  workflow_dispatch: 

jobs:
  build-libvlc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '8512546'      # SDK command line tools version
          ndk-version: '25.1.8937393' # NDK r25b具体版本

      - name: Add sdkmanager to PATH
        run: echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y automake ant autopoint cmake build-essential libtool-bin \
            patch pkg-config protobuf-compiler ragel subversion unzip git \
            openjdk-8-jre openjdk-8-jdk flex python3 wget ninja-build meson

      - name: Build LibVLC for arm64
        run: |
          chmod +x buildsystem/compile.sh
          ./buildsystem/compile.sh -l -a -r arm64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vlc-libvlc-arm64
          path: |
            build-android-arm64/install/lib/*.so
            build-android-arm64/install/include
